### ISSUE TITLE
Almost all of the keyboard shortcuts stopped working after upgrading to 3.25.0

### ISSUE THREAD

**Issue by jason-wihardja** [zenangst/KeyboardCowboy#562]
I have multiple keyboard shortcuts set for multiple apps. None of them are working after updating to 3.25.0.

A few things about my setup that might be useful for tracing issues:
- MacOS Sequoia
- Karabiner Elements installed
- Mac Mouse Fix installed

Previously this setup worked fine. I can confirm this, because downgrading to 3.24.2 makes everything work again.

**Comment by zenangst** [comment]
Hey @jason-wihardja 

Mind sharing which key combinations stopped working?

**Comment by jason-wihardja** [comment]
Would it be useful if I upload my entire config file?
[config.json](https://github.com/user-attachments/files/17559585/config.json)

Using this config, even the close tab action within default group stopped working

**Comment by zenangst** [comment]
Thanks @jason-wihardja,

I'm working on some of the reported issues now.
You supplying a `config.json` will make this debugging a lot easier, thanks!

**Comment by jason-wihardja** [comment]
I am using a macropad to support my productivity, so you may find some weird or unusual key combinations, but those are the keys I assigned to my macropad. Normally, my keystroke pipeline looks something like this:

```
My macropad's original signal (for example the letter A/B) -> Driver maps the signal to some keystrokes (let's assume F15 and F17) -> Keyboard cowboy captures the key -> Do some action.
```

Is there any change to the way you capture keystrokes? For example, instead of capturing the F15/F17 that the driver sends, the software unintentionally captures A/B.

**Comment by zenangst** [comment]
@jason-wihardja Interesting, so it is all the `F-key` related shortcuts that have stopped working for you, correct? The other keys still work as intended?

I did some problems with the migration code (moving the config), that was my first guess that something went wrong there. Did manage to fix another bug, so that is good.

Just need to figure out how I can emulate these keystrokes as I don't have a keyboard with those function keys. Doing some additional research around it now.

**Comment by jason-wihardja** [comment]
Upon further inspection, it's actually the other way around. For example, in Microsoft Edge group here, previous tab works while next tab doesn't work.

![image](https://github.com/user-attachments/assets/327f4005-5e01-4141-abfb-10c1f7d916d7)

**Comment by zenangst** [comment]
@jason-wihardja we just released version `3.25.1`, mind taking that for a spin to see if things work like it should now.

https://github.com/zenangst/KeyboardCowboy/releases/tag/3.25.1

**Comment by zenangst** [comment]
@jason-wihardja would you mind compiling a list of shortcuts that don't work so that I can write some tests for those specific combinations.

Also, one thing worth trying is to try and re-record the shortcuts, just to verify that there isn't a mismatch between old and new configuration and key mapping and lookup.

**Comment by jason-wihardja** [comment]
| Key                                    | Works                   |
|----------------------------------------|-------------------------|
| F13                                    | <ul><li>- [x] </li><ul> |
| F16                                    | <ul><li>- [x] </li><ul> |
| F18                                    | <ul><li>- [x] </li><ul> |
| F19                                    | <ul><li>- [x] </li><ul> |
| F20                                    | <ul><li>- [ ] </li><ul> |
| Home                                   | <ul><li>- [ ] </li><ul> |
| End                                    | <ul><li>- [ ] </li><ul> |
| Cmd + Ctrl + Shift + Opt + Left Arrow  | <ul><li>- [ ] </li><ul> |
| Cmd + Ctrl + Shift + Opt + Right Arrow | <ul><li>- [ ] </li><ul> |

I have also tried re-recording the shortcuts, and it didn't work. There is no difference between the old shortcut and the newly recorded one. The config looks the same.

**Comment by zenangst** [comment]
@jason-wihardja `3.25.0` did include a complete rewrite of the key lookup tables. Shame that this led to you having to downgrade. As soon as I'm done with the CPU & memory improvements, this will be first in line to get fixed.

**Comment by zenangst** [comment]
@jason-wihardja Hey Jason, I've got some good news! I finally figured out why Home & End didn't map properly. I have a fix for that. But I still can't seem to reproduce the issue where you use `Cmd + Ctrl + Shift + Opt + Left Arrow`.

Can you send me the flags that are sent when you press those keys? I'm not sure what Karabiner Event Viewer outputs, but I'm looking for the raw value for the `CGEventFlags`.

I use Key Codes (https://manytricks.com/keycodes/) to look them up.

Here's what I get when it's working for me.

<img width="396" alt="Screenshot 2024-11-05 at 00 26 22" src="https://github.com/user-attachments/assets/2105b4d4-9775-4acc-87fe-17db0d2448f5">

<img width="395" alt="image" src="https://github.com/user-attachments/assets/1791fb68-2183-40d9-90a2-e2e520cc61e0">

**Comment by zenangst** [comment]
@jason-wihardja here's an early release for you to try out!

[Keyboard Cowboy 3.25.2.dmg.zip](https://github.com/user-attachments/files/17624932/Keyboard.Cowboy.3.25.2.dmg.zip)

**Comment by jason-wihardja** [comment]
> @jason-wihardja just a minor follow-up, so that I'm not chasing a red herring. Would you mind enabling notifications for running workflows in the application preferences, just to verify if this is related to the keyboard shortcut trigger or the command that should forward keys to the system?
> 
> <img alt="image" width="1012" src="https://private-user-images.githubusercontent.com/57446/382577968-14acd6a9-1bc0-495f-8a40-677d6ba13e09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NzUzNDQsIm5iZiI6MTczMDc3NTA0NCwicGF0aCI6Ii81NzQ0Ni8zODI1Nzc5NjgtMTRhY2Q2YTktMWJjMC00OTVmLThhNDAtNjc3ZDZiYTEzZTA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDAyNTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNWM3NWZjNTFkZjhlMGFhMTJhN2M2MzQ3MGMyNDk3ZjI3Y2RhYWI3ZWU2MTk3MTU2MTkyMmYxZDY5MzNhZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TLJSU7idYZt0TTDlTRTvGWR6kd0blTydRbm6TSoZc8Q">

I tried this option, but no notifications appeared, even for the working ones

**Comment by jason-wihardja** [comment]
> @jason-wihardja Hey Jason, I've got some good news! I finally figured out why Home & End didn't map properly. I have a fix for that. But I still can't seem to reproduce the issue where you use `Cmd + Ctrl + Shift + Opt + Left Arrow`.
> 
> Can you send me the flags that are sent when you press those keys? I'm not sure what Karabiner Event Viewer outputs, but I'm looking for the raw value for the `CGEventFlags`.
> 
> I use Key Codes ([manytricks.com/keycodes](https://manytricks.com/keycodes/)) to look them up.
> 
> Here's what I get when it's working for me.
> 
> <img alt="Screenshot 2024-11-05 at 00 26 22" width="396" src="https://private-user-images.githubusercontent.com/57446/382951521-2105b4d4-9775-4acc-87fe-17db0d2448f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NzUzNDQsIm5iZiI6MTczMDc3NTA0NCwicGF0aCI6Ii81NzQ0Ni8zODI5NTE1MjEtMjEwNWI0ZDQtOTc3NS00YWNjLTg3ZmUtMTdkYjBkMjQ0OGY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDAyNTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2OTc1MTNjMjNhMDc1ZDdiYjVlZDAwMWFiMjczMDNlNjY5Mzk1ODA2ZWNmZmY1ZjBjMTg5N2MyYjg0NTQwMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.clmVfNf8FRNMgR2mqIuwo_P0pH-CJKK2RnqZIqy6-Cg"> <img alt="image" width="395" src="https://private-user-images.githubusercontent.com/57446/382951723-1791fb68-2183-40d9-90a2-e2e520cc61e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NzUzNDQsIm5iZiI6MTczMDc3NTA0NCwicGF0aCI6Ii81NzQ0Ni8zODI5NTE3MjMtMTc5MWZiNjgtMjE4My00MGQ5LTkwYTItZTJlNTIwY2M2MWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDAyNTA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1ZTZkMWFlNWM0OTUxOWU0MzRiMDBhYmYwNjUwYzVmYTk0ZjVjNzg3MjhhMjNkNzI0MDg5NDAzM2RmMjNjYjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kmks75fpmxq2jXD1KDwbwyTi_7o-vB9BcTRdKYgxwcE">

Here are the keycodes for every key combination I listed on the table above

<img width="382" alt="image" src="https://github.com/user-attachments/assets/ee31bb00-2248-4f61-a617-0d64ccff51f8">

_(the last one is F20, the Key Codes app fails to display the character/key)_

Using v3.52.2, I can confirm that Home/End now works. But other non-working keys are still not working.

**Comment by zenangst** [comment]
Hey @jason-wihardja,

I'm still trying to figure this out. If you don't mind, I'd like to test your configuration in the test suite so I can use it for future regression testing. Is that okay with you?

I tried to match `Control+Option+Command+ArrowRight` against your configuration, but I can't find any reference to it. Also, it seems a bit odd that `F20` doesn't have any modifiers attached to it. Maybe it's a bug in Key Codes, since I can't test it locally (I don't have a keyboard with more than 12 F-keys). In theory, it should share the same modifiers as the rest of the F-keys.

By the way, what are you using `Karabiner Elements` for? I just want to make sure these two applications aren't actually in conflict with each other.

### Table Overview
| Key                                    | Works                   |
|----------------------------------------|-------------------------|
| F13                                    | <ul><li>- [x] </li><ul> |
| F16                                    | <ul><li>- [x] </li><ul> |
| F18                                    | <ul><li>- [x] </li><ul> |
| F19                                    | <ul><li>- [x] </li><ul> |
| F20                                    | <ul><li>- [ ] </li><ul> |
| Home                                   | <ul><li>- [x] </li><ul> |
| End                                    | <ul><li>- [x] </li><ul> |
| Cmd + Ctrl + Shift + Opt + Left Arrow  | <ul><li>- [ ] </li><ul> |
| Cmd + Ctrl + Shift + Opt + Right Arrow | <ul><li>- [ ] </li><ul> |

**Comment by jason-wihardja** [comment]
Sure, you may use the config. I'm currently away for a business trip, so I don't have my macropad with me right now. Will test again the key combination once I get back home.

And yes, seems like I included `Control+Option+Command+ArrowRight` by mistake. It's a key that Karabiner captured.

For context, my karabiner captured different key combinations than the one being mapped in Keyboard Cowboy, in particular the ones that work globally regardless of app. I mainly use Keyboard Cowboy for key combinations that have different actions depending on apps, which is something Karabiner can't really do easily.

**Comment by zenangst** [comment]
@jason-wihardja could you let me know when you have time to re-test the latest version?
While at work, I checked the standard Apple keyboards and their F-keys only reach F19.
So perhaps it is correct that the additional modifiers should be dropped for that key.

**Comment by jason-wihardja** [comment]
Ok, so I've gotten back from the trip. I noticed that you've released v3.25.3. Let me re-test them. And what do you mean by `additional modifiers should be dropped`? I didn't press cmd, shift, or any other modifier when hitting F20. Previously it maps just fine. But let me re-test everything first and report back to you

**Comment by jason-wihardja** [comment]
So, after I test some more, it seems that for me, the behavior is the same as before. It's still not working. Using `Key Codes`, I can see that for buttons that are mapped successfully, `Key Codes` now shows a different keystroke, which is the key I map the button into, but for buttons that are not working, the behavior is still the same. It is as if the Keyboard Cowboy app is not running

**Comment by zenangst** [comment]
> And what do you mean by additional modifiers should be dropped? I didn't press cmd, shift, or any other modifier when hitting F20.

What I meant was, if you compare F13 or F16 with F20, you'll notice that the flags for F1-F19 are different.

Here's the flags for F1-F19:
```
NX_SECONDARYFNMASK / kCGEventFlagMaskSecondaryFn / NSFunctionKeyMask
	= 8388608 / 0x800000
NX_NONCOALSESCEDMASK / kCGEventFlagMaskNonCoalesced
	= 256 / 0x100
```

Now, let's look at your F20:
```
NX_NONCOALSESCEDMASK / kCGEventFlagMaskNonCoalesced
	= 256 / 0x100
```

I made an assumption that all F-keys should use the function key mask. However, I believe this assumption was incorrect. The keys from F1 to F19 should have the function key mask, while the remaining keys should use the non-coalesced flag.

**Comment by CosmicToast** [comment]
This is likely related (my bindings also broke with 3.25.0, I only got around to trying to report now).
My situation in particular is that I bind `cmd-shift-[…]`, which works, but not if I use my caps lock (which is rebound by the system to cmd).

For example, I use cmd-shift-k to open iterm with kalker.
As per key codes, the modifiers are different:
`capslock as cmd` + shift + k: 0x28 keycode, 0x120112 modifiers:
* NX_SHIFTMASK / kCGEventFlagMaskShift / NSShiftKeyMask = 131072 / 0x20000
* NX_DEVICELSHIFTKEYMASK = 2 / 0x2
* NX_COMMANDMASK / kCGEventFlagMaskCommand / NSCommandKeyMask = 1048576 / 0x100000
* NX_DEVICERCMDKEYMASK = 16 / 0x10
* NX_NONCOALSESCEDMASK / kCGEventFlagMaskNonCoalesced = 256 / 0x100

`real cmd` + shift + k: 0x28 keycode, 0x12010a modifiers:
* NX_SHIFTMASK / kCGEventFlagMaskShift / NSShiftKeyMask = 131072 / 0x20000
* NX_DEVICELSHIFTKEYMASK = 2 / 0x2
* NX_COMMANDMASK / kCGEventFlagMaskCommand / NSCommandKeyMask = 1048576 / 0x100000
* NX_DEVICELCMDKEYMASK = 8 / 0x8
* NX_NONCOALSESCEDMASK / kCGEventFlagMaskNonCoalesced = 256 / 0x100

The difference is that the caps lock cmd variant is reported as RCMD (right side cmd) rather than LCMD (left side cmd).
I'm noticing that, indeed, if I use the right cmd it doesn't go through either.
In 3.25.2, I also noticed that if I define a shortcut with the right cmd (e.g. rcmd, shift, k) then neither the right nor the left cmd can trigger it.

Looks like you internally treat the two as equivalent (despite their different codes), as per ShortcutResolverTests.swift `    // Verify Command + Control + Shift + Option + Left Arrow`.

One approach you could take is instead of checking directly for RCMD or LCMD, instead checking for `>0` when applying a `0x18` mask. (i.e. cmd is in use if `0x18 & modifiers > 0`), but this is just me guessing based on looking around in the code for a few minutes.
I'm fairly short on time lately, but if you need any help I could try and carve out an hour or two maybe next weekend to help out (at least with this particular instance of the problem, and try to see if there's any other patterns along these lines; though note I have no swift experience so far).

**Comment by zenangst** [comment]
Thanks a bunch for your response, @CosmicToast!

I'm curious, are you using third-party software to remap your caps lock key to command, or did you do that through System Settings? I'm wondering why it ends up as the right command key, maybe that's by design.

While trying to figure this out, I found a small issue with how keyboard shortcuts are registered in Keyboard Cowboy. It doesn't check if each key is in the correct left or right position. I think this might be part of the problem we're seeing here.

So, if you hold down left-shift + right command, it will be registered as right-shift & right command. Only one of the keys have to be on the right side for all of them to be registered as such.

**Comment by zenangst** [comment]
@CosmicToast @jason-wihardja 
I made a pre-release version that I'd like you to try out.
[Keyboard Cowboy 3.25.4.dmg.zip](https://github.com/user-attachments/files/17708633/Keyboard.Cowboy.3.25.4.dmg.zip)

**Comment by zenangst** [comment]
@CosmicToast @jason-wihardja @CosmicToast @jason-wihardja found a minor issue in the previous version that I shared (so I deleted that comment). Here is a freshly brewed version.
[Keyboard Cowboy 3.25.4.dmg.zip](https://github.com/user-attachments/files/17708814/Keyboard.Cowboy.3.25.4.dmg.zip)

**Comment by CosmicToast** [comment]
Running straight from it, the behaviour is a bit different:
When I record the shortcut using the rebound caps, it now registers as left side.
So I can't execute it using the same shortcut (using caps), but I can now execute it using the left side cmd (but not the right side cmd).

> I'm curious, are you using third-party software to remap your caps lock key to command, or did you do that through System Settings? I'm wondering why it ends up as the right command key, maybe that's by design.

System settings, probably coincidental (they had to pick one or the other, in the end).

**Comment by zenangst** [comment]
@CosmicToast 

Thanks for testing the new version.

I've started a major overhaul of the key capture process. This way, each key is clearly marked, like the left or right command. I think this will fix the mix-ups.
As mentioned earlier, the flaw in the design that we have right now is that keys will either be reported as being a part of the left or right side, not both.

I set up Karbiner elements so that my caps lock key can either be the escape key (when tapped) or the left control key (when held). I know this might not be the most straightforward way to do it, but it's the way I chose to avoid any confusion.

But this won't solve the problem with the caps lock key being reported as the right command. If you want to use both the left and right sides at the same time, you'll need to change the workflows for different combinations.

I'll keep you posted on any progress that I make.

Thanks for your patience.

**Comment by zenangst** [comment]
@CosmicToast @jason-wihardja 

Here is an update on the current state of things.
I had a long code session with a friend this evening, and we looked into implementing uniqueness for individual modifiers. 

What this means is that you can now make commands that involve left, right, or both of the command modifiers (this was not possible before based on the way we determined the modifiers' position).

In order to do this, we had to perform a migration to the new data structure.
This means that some of the bindings (guessing the ones that are not currently working) would have to be re-recorded. All other existing recordings (that don't mix and match left & right modifiers) should be migrated just fine.

In addition to making the transition to the new data structure, a backup will be created of the current configuration and stored in `~/.config/keyboardcowboy/backups/` with the current format:

```
config.{currentBuild}.json
```

This should help with rolling back to older versions if we need additional changes to the data structure in the future.

I've successfully migrated my own configuration without hitches (thus far).
Taking it for a spin tomorrow at work to see if there are any additional bugs that need smashing. If I come up empty, would you like to be the first to try out this new version to see if that brings us closer to the finish line?

**Comment by jason-wihardja** [comment]
Sure. Would love to try that out. Because so far I had no other solutions other than downgrade to 3.24.2. Although I believe that @CosmicToast's problem may be different compared to mine, but who knows. The new data structure hopefully can solve both problems.

**Comment by zenangst** [comment]
@jason-wihardja @CosmicToast here is another pre-release version that you can test with.
Note the previous things that I mentioned: it will create a backup before migrating to a new data structure. Hopefully, you have your own backups as well (just to be safe).

Keep in mind that you also might have to re-record the keyboard shortcuts that previously didn't work as intended.

[Keyboard Cowboy 3.25.4.dmg.zip](https://github.com/user-attachments/files/17730357/Keyboard.Cowboy.3.25.4.dmg.zip)

**Comment by jason-wihardja** [comment]
Ok, so I've tried the new one and here's how the re-recorded config looks like
[config.json](https://github.com/user-attachments/files/17732924/config.json)

From this config, the only non-working buttons are:
- F20
- Ctrl + Cmd + Alt + Shift + Left Arrow (the config somehow recorded an extra fn being pressed)
- Ctrl + Cmd + Alt + Shift + Right Arrow (the config also somehow recorded an extra fn being pressed)

**Comment by zenangst** [comment]
@jason-wihardja Thanks for following up. I'll take another look at your config when life allows and continue to dig into this.

I have yet to do anything about F20, will also take a look at that one.
Are all of the modifiers that you are using located on the left side of the keyboard?

**Comment by zenangst** [comment]
@jason-wihardja just tried to record `Ctrl + Cmd + Alt + Shift + Left Arrow`, and it does in fact record it with the function key. But that seems correct as all arrow keys should include the function modifier.

Key Codes include the same modifier flags when I test it there.

![image](https://github.com/user-attachments/assets/2b92c338-f955-46d5-abd3-a58db7e556e3)

![image](https://github.com/user-attachments/assets/3c3e5962-40a8-4866-ad6e-161e5860b863)

**Comment by zenangst** [comment]
Yeah, and the raw event that I get from the mach port includes the function key.
However, it seems that we didn't properly map this before, we just took the raw key code for arrow keys. Perhaps that is the issue we are seeing.

I'll dig a bit deeper.

Do you trigger the arrow shortcuts mentioned above using your macropad?
If so, can it be configured to include that mask?

**Comment by zenangst** [comment]
@jason-wihardja I think I'm on to something now, I'm cooking a new version now for you to test. Just give me a minute for it to build.

**Comment by zenangst** [comment]
Here is the new version, don't forget to re-record the shortcut before testing.

[Keyboard Cowboy 3.25.4.dmg.zip](https://github.com/user-attachments/files/17733517/Keyboard.Cowboy.3.25.4.dmg.zip)

**Comment by jason-wihardja** [comment]
> Do you trigger the arrow shortcuts mentioned above using your macropad? If so, can it be configured to include that mask?

Yes, I'm using my macropad. But I think I can't really include/exclude individual buttons/modifiers as the way I recorded a macro is through a software where it has a similar record functionality as yours. And since the recorded macro is being saved directly into the device's onboard memory, I don't really have the necessary skill to access or modify it in a manner that's akin to being as raw as editing the json in yours.

> Here is the new version, don't forget to re-record the shortcut before testing.
> 
> [Keyboard Cowboy 3.25.4.dmg.zip](https://github.com/user-attachments/files/17733517/Keyboard.Cowboy.3.25.4.dmg.zip)

Unfortunately, it still doesn't fix `F20` and `Ctrl + Cmd + Alt + Shift + Left/Right Arrow`. And it broke something else.

Remember the workaround that I mentioned before where I now used `Insert` button in place for `F20` because it's working, previously it was recorded as `fn + Insert`, now it is recorded as `Insert` only and it broke that shortcut. However, if I plug in the previous config, where things are still configured as `fn + Insert`, without re-recording, the shortcut for that button still works.

**Comment by zenangst** [comment]
@jason-wihardja Are you using the macropad or the regular keyboard to record?

The last change that I made was to revert the change where the function gets invoked when recording arrow keys, F-keys etc. Instead, it will record these as a single special key. I thought this would be as this is how we did it before the 3.25.0 release.

**Comment by zenangst** [comment]
@jason-wihardja, can you let me know which keyboard locale you're using? I'm adding some extra tests to the `KeyCodes` framework that I'm using to create virtual key tables for keyboard shortcuts.

**Comment by jason-wihardja** [comment]
> The last change that I made was to revert the change where the function gets invoked when recording arrow keys, F-keys etc. Instead, it will record these as a single special key. I thought this would be as this is how we did it before the 3.25.0 release.

Yes, since I often do upgrades/downgrades, this is something I notice as well. However, things work fine in 3.24.x. My keys are recorded without `fn` key, and it work, whereas in the latest version you uploaded, things seem only work if the button is recorded with `fn` key included (which the latest build of 3.25.4 fails to do)

> Can you let me know which keyboard locale you're using?

I'm using standard US ANSI layout

**Comment by jason-wihardja** [comment]
Using the latest version you uploaded, this is the config that has everything working (with some buttons like `F20` reassigned to `Insert`). I wasn't able to record all these through the recorder due to the missing `fn` modifier I mentioned before, so I edited the file directly.

[config.json](https://github.com/user-attachments/files/17769502/config.json)

Using this new config, the functionality is equivalent to what I was achieving with version 3.24.2 and the config I attached previously [here](https://github.com/zenangst/KeyboardCowboy/issues/562#issuecomment-2444662104).

**Comment by zenangst** [comment]
@jason-wihardja here is a new version for test 🤞

[Keyboard Cowboy 3.25.4.dmg.zip](https://github.com/user-attachments/files/17773581/Keyboard.Cowboy.3.25.4.dmg.zip)

**Comment by zenangst** [comment]
@jason-wihardja  I just released 3.25.4, because it included additional other fixes that I wanted to get out there, let me know how it goes.

**Comment by jason-wihardja** [comment]
Ok, now all the function buttons are working from F13 to F20. `Insert` and `Ctrl + Cmd + Alt + Shift + Left/Right Arrow` are the only two things that are still broken. I noticed that in the previous version, `Insert` is recorded as `fn + Insert` whereas in this new version, it is recorded as `Insert` only. Directly editing the config to `fn + Insert` in the new version works though.

**Comment by CosmicToast** [comment]
Just here to confirm that my issues (post re-record) are resolved with 3.25.4.
Thanks!

**Comment by zenangst** [comment]
@CosmicToast Thanks for following up.

**Comment by ww7** [comment]
From my side, found Cmd+Opt+Shift+ not working with `,./`

P.S.: Confirming that the new version is keyboard language agnostic.

**Comment by zenangst** [comment]
Hi @ww7, can you please share more details about the shortcuts that aren't working? I recently created a keyboard trigger with `Cmd+Opt+Shift+,` and it worked perfectly. I tried both the left and right sides of the keyboard.

Have you tried re-recording the shortcut?

If you're comfortable sharing, a screenshot (or a copy of your config) of the workflow in question would be super helpful in debugging.

Thanks so much for reaching out about the language-agnostic part! I'm glad you liked it. 😊

It's one of those happy accidents that I didn't even set out to fix that specifically. Haha! 🤓

**Comment by ww7** [comment]
I'm sorry, missed `Ctrl`, not working `Cmd+Opt+Ctrl+Shift` + `,./`

**Comment by zenangst** [comment]
Hey @ww7, that's an interesting find! Unfortunately, it seems like they're already captured by the system before they reach Keyboard Cowboy.

I did some digging and it looks like the `,` and `.` modifiers do the following:

> The key combination Shift + Control + Option + Command + Comma (,) in macOS triggers a system-level diagnostic tool called Tailspin. When activated, the screen may flash briefly, indicating that the system is capturing diagnostic data.

https://discussions.apple.com/thread/254787050?sortBy=rank

> The key combination Shift + Control + Option + Command + Period (.) in macOS triggers the sysdiagnose utility, a system-level diagnostic tool. When activated, the screen may flash briefly, indicating that the system is capturing extensive diagnostic data, including system logs, kernel logs, and other relevant information. 

I tried closing Keyboard Cowboy & Karbiner-Elements to see if any other apps were interfering, but I still get the same result. It seems like the Key Codes are trying to capture the event, but it's not working.

**Comment by zenangst** [comment]
But I can't replicate the arrow keys, this shortcut works just fine when I test it.

<img width="1106" alt="image" src="https://github.com/user-attachments/assets/dce7014a-a739-4805-8d26-0d43e08a160e">

**Comment by ww7** [comment]
Okay! With Karbiner-Elements diagnostic shortcuts `.` and `,` can be disabled, I'm using 
```
{
    "description": "Disable command+control+option+shift+. which triggers sysdiagnose.",
    "manipulators": [
        {
            "from": {
                "key_code": "period",
                "modifiers": { "mandatory": ["command", "control", "option", "shift"] }
            },
            "type": "basic"
        }
    ]
}
```
and 
```
{
    "description": "Disable command+control+option+shift+, which triggers WiFi logging.",
    "manipulators": [
        {
            "from": {
                "key_code": "comma",
                "modifiers": { "mandatory": ["command", "control", "option", "shift"] }
            },
            "type": "basic"
        }
    ]
}
```
and seems it can be used via KE, but does not arraving to the KC!

**Comment by zenangst** [comment]
Aw interesting. So you are just disabling them?
Will the app `Key Codes` show any events? To me it seems like KE is short-circuiting the shortcut rather than actually forwarding it to any other app that wants to receive it.

**Comment by jason-wihardja** [comment]
Weirdly, in version 3.24.2, those combinations work just fine, whereas in 3.25.x, it fails to detect the shortcut

**Comment by zenangst** [comment]
@jason-wihardja which shortcuts are you referring to?

**Comment by zenangst** [comment]
@jason-wihardja well the system bound periods and commas never worked.

still trying to figure out why I have zero issues with all for modifiers and the arrow keys.

The commands that are inside the workflows, are those also keyboard commands, if so, have you tried re-recording them?

**Comment by jason-wihardja** [comment]
> The commands that are inside the workflows, are those also keyboard commands, if so, have you tried re-recording them?

I haven't. But assuming that I have never re-record anything inside any workflows during the testing so far, only reassigning buttons that triggers the workflow and managed to get things working when the broken workflow gets reassigned to a different trigger, then the problem must be in the recorder part, isn't it?

**Comment by zenangst** [comment]
Well there could be some incompatible combinations because they both use the same functionality for recording. Recording, indexing and resolving has been refactored, so all of the parts have been under the loop and changed in some way.

**Comment by jason-wihardja** [comment]
> still trying to figure out why I have zero issues with all for modifiers and the arrow keys

Ok, maybe here's something for you to try to reproduce the issue.

First, install Mac Mouse Fix (30 days trial available), then assign a button (for example, button 3/scroll wheel) to `Ctrl + Cmd + Alt + Shift + Left/Right Arrow`. For example, in my case I'm using button 6 like this
<img width="540" alt="image" src="https://github.com/user-attachments/assets/317bf971-d4d0-4e3f-9439-40b4cf92201b">

Then in Keyboard Cowboy, try recording a shortcut, but you press the mouse scroll wheel instead, which causes Keyboard Cowboy to detect the combination. This, in my setup, doesn't work. Also, `Insert` button still didn't work correctly.

**Comment by zenangst** [comment]
@jason-wihardja Thanks a bunch, Jason! I'll give the Mac Mouse Fix a try with those instructions. I'll let you know what it says.

I'll also check out the 'Insert' key and why that is causing issues.

I got some other bugs fixed today that were bugging me, but life got in the way and I couldn't look into this one more. I might be able to give it a shot later this week though.

Thanks again for being so patient! ❤️

**Comment by jason-wihardja** [comment]
Sorry for the very late reply, I was very busy last week.

I can confirm that the shortcut now works. Seems like my macropad recorder also added some extra flags, similar to what Mac Mouse Fix produces. But the new version handles it well. So, I guess what's left is the `Insert` button.

**Comment by zenangst** [comment]
@jason-wihardja what is the key code and modifiers for `Insert`? Is it a part of your previous configuration that you shared?

**Comment by jason-wihardja** [comment]
It was previously included in the config I uploaded [here](https://github.com/zenangst/KeyboardCowboy/issues/562#issuecomment-2477931464). One example of the shortcut utilizing this button is Shuffle shortcut under Spotify app group. But I guess that was recorded before the tweaks that you did with the `fn` button. Let me know if you need me to re-record it using the latest version

**Comment by zenangst** [comment]
@jason-wihardja I think it's a good idea to record the keyboard shortcut again using the latest version of the code. That way, we don't accidentally patch a permutation that might have been recorded with an outdated implementation. Just to double-check!

**Comment by zenangst** [comment]
@jason-wihardja I see that your Shuffle command has been stored as `?`, which is clearly wrong.

```json
"trigger" : {
              "keyboardShortcuts" : {
                "passthrough" : false,
                "shortcuts" : [
                  {
                    "id" : "F9D4162A-BADF-47D4-A63B-6A6F17855323",
                    "key" : "?⃝",
                    "modifiers" : [
                      "fn"
                    ]
                  }
                ]
              }
            }
```

Would you mind sharing the key code for `Insert`?

**Comment by jason-wihardja** [comment]
Here is the keycode

![image](https://github.com/user-attachments/assets/44a761a4-b5dd-41fd-99a9-e213e030d4b0)

**Comment by zenangst** [comment]
@jason-wihardja, could you please expand on the modifiers? I'd love to get a better idea of which ones to attach. Thanks a bunch!

**Comment by jason-wihardja** [comment]
Here's how it looks like

![image](https://github.com/user-attachments/assets/5524ad43-4951-4619-9a6a-d939b0fce84f)

**Comment by RKitSeal** [comment]
3.24.2 is the final version that _executes_ workflows in response to my keyboard shortcut triggers when sent via macOS's Screen Sharing (VNC).

However, the current version (3.26.1) has no problem _recording_ keyboard shortcut triggers over Screen Sharing—it just never executes them.

Here's an example config in case it's useful:
> NOTE: use `/bin/date` or GNU-coreutils `gdate` if missing [uutils-coreutils](https://github.com/uutils/coreutils)
```json
[
  {
    "groups" : [
      {
        "color" : "#000",
        "id" : "71230804-F549-4F5A-B515-6C8CBA8533F8",
        "name" : "text",
        "symbol" : "folder",
        "workflows" : [
          {
            "commands" : [
              {
                "scriptCommand" : {
                  "kind" : "sh",
                  "meta" : {
                    "enabled" : true,
                    "id" : "86D96872-894F-40E3-B944-E1AB86E797A2",
                    "name" : "Run Shell Script",
                    "variableName" : "datetime_stamp"
                  },
                  "source" : {
                    "inline" : {
                      "_0" : "#!\/bin\/sh\n\n\/opt\/homebrew\/bin\/udate -u +%Y-%m-%dT%H.%M.%S.%NZ | cut -c -26,30 | tr -d '\\n'"
                    }
                  }
                }
              },
              {
                "textCommand" : {
                  "kind" : {
                    "insertText" : {
                      "_0" : {
                        "actions" : [

                        ],
                        "input" : "$datetime_stamp",
                        "meta" : {
                          "enabled" : true,
                          "id" : "A167F4F6-98E9-4FA7-8346-7A504E633919",
                          "name" : ""
                        },
                        "mode" : "Instant"
                      }
                    }
                  }
                }
              }
            ],
            "execution" : "serial",
            "id" : "77301793-D11E-4EFF-85DD-73059A28BFA0",
            "name" : "file_datetime",
            "trigger" : {
              "keyboardShortcuts" : {
                "shortcuts" : [
                  {
                    "id" : "ACB7BC81-B645-47C2-95C2-4BD988C9D28D",
                    "key" : "f",
                    "modifiers" : [
                      "$",
                      "~"
                    ]
                  }
                ]
              }
            }
          }
        ]
      }
    ],
    "id" : "76364457-865B-4E99-9281-AF50231A231B",
    "name" : "Default configuration",
    "userModes" : [

    ]
  }
]
```

**Comment by zenangst** [comment]
@RKitSeal, if this is the only command that is unable to run, then it is probably not related to this issue but rather an issue with running shell scripts.

**Comment by zenangst** [comment]
@RKitSeal I tried this out and it worked like intended:

<img width="487" alt="Image" src="https://github.com/user-attachments/assets/16161ab0-0878-472e-8a41-ed8321ffeefc" />

I'm working on better debugging for scripts that don't run as they should.

**Comment by zenangst** [comment]
In the next version, an alert will pop-up when a shell script fails. That should help with debugging failing scripts :)

**Comment by RKitSeal** [comment]
I ought to clarify: I have Keyboard Cowboy running on the remote host, not the local macOS client accessing it by Screen Sharing. I have most shortcuts changed or disabled on the client so as to not override.

> [@RKitSeal](https://github.com/RKitSeal) I tried this out and it worked like intended:
> <img alt="Image" width="487" src="https://private-user-images.githubusercontent.com/57446/418759967-16161ab0-0878-472e-8a41-ed8321ffeefc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEwNDA4NDQsIm5iZiI6MTc0MTA0MDU0NCwicGF0aCI6Ii81NzQ0Ni80MTg3NTk5NjctMTYxNjFhYjAtMDg3OC00NzJlLThhNDEtZWQ4MzIxZmZlZWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzAzVDIyMjIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNjk1MGY0OWZmZjVkOGIzZjQ1NjA3YmMzOTJkOTE1ZTZhZjg1N2UwOTc5MDdhZTZjNWFjMGU2MGI0ZTI0MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dD004Dd-b92MXQbIP5hVGtRo9O-nTpQr9wxXIBABubQ">
> 
> I'm working on better debugging for scripts that don't run as they should.

That isn't working for me. What I provided was solely an example—none of my shortcuts have worked over Screen Sharing after 3.25.0.

Karabiner-Events doesn't pick up any activity over Screen Sharing, but Key-Codes does:
![Image](https://github.com/user-attachments/assets/effbb423-fd92-4436-96ee-4e5f21b138cc)

**Comment by RKitSeal** [comment]
> [@RKitSeal](https://github.com/RKitSeal), if this is the only command that is unable to run, then it is probably not related to this issue but rather an issue with running shell scripts.

If I go to the physical machine, everything runs marvellously—almost twice as fast as my AppleScripts that accomplish the same task ⏩

**Comment by zenangst** [comment]
OOOOOOOOOOOOOOOH!

Ah, I didn't catch that part, thanks for clarifying!
This scenario I haven't tried out before but what an amazing idea! :)

I think I need to setup a Virtual Machine where I can replicate your scenario and try it out.
Curious to see how mach port events are sent from Screen Sharing over to the remote host.

Out of curiosity, are both remote & local machine using the same input source? (Like English)?

**Comment by RKitSeal** [comment]
Yes, both are set to Canadian English

**Comment by RKitSeal** [comment]
UTM made it remarkably easy to set up a VM

Double-nested Screen Sharing-ception:
![Image](https://github.com/user-attachments/assets/06e0b419-24f1-4b2c-ab27-f4d13dbb7d57)
